/* AUTOMATISCH GEGENEREERD — niet met de hand aanpassen.
   Draai `node scripts/build-icons.mjs` na het toevoegen van een icoon.

   Expliciete registry van de 164 iconen die de site gebruikt, zodat
   de bundler de rest van Lucide weg kan schudden. */
import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlarmClock,
  Anchor,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  BarChart2,
  Bell,
  Blocks,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  CalendarX,
  Camera,
  Car,
  ChartColumn,
  ChartLine,
  Check,
  ChevronDown,
  Circle,
  CircleHelp,
  Clipboard,
  ClipboardList,
  Clock,
  Cloud,
  CodeXml,
  Cog,
  Compass,
  Contact,
  CreditCard,
  Database,
  Droplets,
  Dumbbell,
  Euro,
  Eye,
  FileCheck,
  FileSpreadsheet,
  FileText,
  Files,
  Film,
  FilterX,
  Flag,
  Funnel,
  Gauge,
  Gift,
  GitMerge,
  Globe,
  GraduationCap,
  Grid,
  Hammer,
  Hand,
  HandCoins,
  HandHeart,
  Handshake,
  HardHat,
  Heart,
  HeartHandshake,
  Home,
  Hourglass,
  Image,
  Images,
  Inbox,
  Info,
  Instagram,
  Languages,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Leaf,
  Lightbulb,
  Link,
  Link2,
  List,
  ListChecks,
  ListOrdered,
  LogOut,
  Mail,
  MailX,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareText,
  Monitor,
  MousePointerClick,
  Newspaper,
  Package,
  PackageCheck,
  Paintbrush,
  Palette,
  PanelsTopLeft,
  PenLine,
  PenTool,
  Percent,
  Phone,
  PhoneCall,
  PhoneOff,
  PieChart,
  Play,
  Plug,
  Plus,
  Quote,
  Receipt,
  RefreshCw,
  Repeat,
  Rocket,
  Route,
  Scroll,
  Search,
  SearchCheck,
  SearchX,
  Send,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sliders,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Tag,
  Target,
  Ticket,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Type,
  UploadCloud,
  User,
  UserCheck,
  UserPlus,
  UserSearch,
  UserX,
  Users,
  Video,
  Wallet,
  Wind,
  Workflow,
  Wrench,
  X,
  Zap,
  ZapOff,
} from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  "activity": Activity,
  "alarm-clock": AlarmClock,
  "alert-triangle": TriangleAlert,
  "anchor": Anchor,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "award": Award,
  "badge-check": BadgeCheck,
  "bar-chart-2": BarChart2,
  "bar-chart-3": ChartColumn,
  "bell": Bell,
  "blocks": Blocks,
  "book-open": BookOpen,
  "bot": Bot,
  "boxes": Boxes,
  "brain": Brain,
  "briefcase": Briefcase,
  "building-2": Building2,
  "calculator": Calculator,
  "calendar": Calendar,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "calendar-plus": CalendarPlus,
  "calendar-range": CalendarRange,
  "calendar-x": CalendarX,
  "camera": Camera,
  "car": Car,
  "check": Check,
  "chevron-down": ChevronDown,
  "circle": Circle,
  "clipboard": Clipboard,
  "clipboard-list": ClipboardList,
  "clock": Clock,
  "cloud": Cloud,
  "code-2": CodeXml,
  "cog": Cog,
  "compass": Compass,
  "contact": Contact,
  "credit-card": CreditCard,
  "database": Database,
  "droplets": Droplets,
  "dumbbell": Dumbbell,
  "edit-3": PenLine,
  "euro": Euro,
  "eye": Eye,
  "file-check": FileCheck,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "files": Files,
  "film": Film,
  "filter": Funnel,
  "filter-x": FilterX,
  "flag": Flag,
  "gauge": Gauge,
  "gift": Gift,
  "git-merge": GitMerge,
  "globe": Globe,
  "graduation-cap": GraduationCap,
  "grid": Grid,
  "hammer": Hammer,
  "hand": Hand,
  "hand-coins": HandCoins,
  "hand-heart": HandHeart,
  "handshake": Handshake,
  "hard-hat": HardHat,
  "heart": Heart,
  "heart-handshake": HeartHandshake,
  "help-circle": CircleHelp,
  "home": Home,
  "hourglass": Hourglass,
  "image": Image,
  "images": Images,
  "inbox": Inbox,
  "info": Info,
  "instagram": Instagram,
  "languages": Languages,
  "layers": Layers,
  "layout": PanelsTopLeft,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "layout-template": LayoutTemplate,
  "leaf": Leaf,
  "lightbulb": Lightbulb,
  "line-chart": ChartLine,
  "link": Link,
  "link-2": Link2,
  "list": List,
  "list-checks": ListChecks,
  "list-ordered": ListOrdered,
  "log-out": LogOut,
  "mail": Mail,
  "mail-x": MailX,
  "map": Map,
  "map-pin": MapPin,
  "menu": Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "message-square-text": MessageSquareText,
  "monitor": Monitor,
  "mouse-pointer-click": MousePointerClick,
  "newspaper": Newspaper,
  "package": Package,
  "package-check": PackageCheck,
  "paintbrush": Paintbrush,
  "palette": Palette,
  "pen-tool": PenTool,
  "percent": Percent,
  "phone": Phone,
  "phone-call": PhoneCall,
  "phone-off": PhoneOff,
  "pie-chart": PieChart,
  "play": Play,
  "plug": Plug,
  "plus": Plus,
  "quote": Quote,
  "receipt": Receipt,
  "refresh-cw": RefreshCw,
  "repeat": Repeat,
  "rocket": Rocket,
  "route": Route,
  "scroll": Scroll,
  "search": Search,
  "search-check": SearchCheck,
  "search-x": SearchX,
  "send": Send,
  "settings": Settings,
  "settings-2": Settings2,
  "shield": Shield,
  "shield-check": ShieldCheck,
  "ship": Ship,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "shuffle": Shuffle,
  "sliders": Sliders,
  "sliders-horizontal": SlidersHorizontal,
  "smartphone": Smartphone,
  "smile": Smile,
  "sparkles": Sparkles,
  "sprout": Sprout,
  "star": Star,
  "sun": Sun,
  "tag": Tag,
  "target": Target,
  "ticket": Ticket,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  "truck": Truck,
  "type": Type,
  "upload-cloud": UploadCloud,
  "user": User,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  "user-search": UserSearch,
  "user-x": UserX,
  "users": Users,
  "video": Video,
  "wallet": Wallet,
  "wind": Wind,
  "workflow": Workflow,
  "wrench": Wrench,
  "x": X,
  "zap": Zap,
  "zap-off": ZapOff,
}
