/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AlgemeneVoorwaardenRouteImport } from './routes/algemene-voorwaarden'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GratisWebsitescanRouteImport } from './routes/gratis-websitescan'
import { Route as OverMegaonlineRouteImport } from './routes/over-megaonline'
import { Route as PrivacyverklaringRouteImport } from './routes/privacyverklaring'
import { Route as VeelgesteldeVragenRouteImport } from './routes/veelgestelde-vragen'
import { Route as BranchesActiviteitenbedrijvenRouteImport } from './routes/branches/activiteitenbedrijven'
import { Route as BranchesDienstverlenersRouteImport } from './routes/branches/dienstverleners'
import { Route as BranchesNonProfitsRouteImport } from './routes/branches/non-profits'
import { Route as BranchesOfferteaanvragenRouteImport } from './routes/branches/offerteaanvragen'
import { Route as BranchesReserveringenRouteImport } from './routes/branches/reserveringen'
import { Route as BranchesVerhuurbedrijvenRouteImport } from './routes/branches/verhuurbedrijven'
import { Route as DienstenConversieWebsiteRouteImport } from './routes/diensten/conversie-website'
import { Route as DienstenGroeiPartnershipRouteImport } from './routes/diensten/groei-partnership'
import { Route as DienstenIntegratiesRouteImport } from './routes/diensten/integraties'
import { Route as DienstenSeoRouteImport } from './routes/diensten/seo'
import { Route as DienstenStarterWebsiteRouteImport } from './routes/diensten/starter-website'
import { Route as DienstenWebsiteOptimalisatieRouteImport } from './routes/diensten/website-optimalisatie'
import { Route as DienstenWebsiteRedesignRouteImport } from './routes/diensten/website-redesign'
import { Route as DienstenWerkenBijWebsitesRouteImport } from './routes/diensten/werken-bij-websites'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeneVoorwaardenRoute = AlgemeneVoorwaardenRouteImport.update({
  id: '/algemene-voorwaarden',
  path: '/algemene-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GratisWebsitescanRoute = GratisWebsitescanRouteImport.update({
  id: '/gratis-websitescan',
  path: '/gratis-websitescan',
  getParentRoute: () => rootRouteImport,
} as any)
const OverMegaonlineRoute = OverMegaonlineRouteImport.update({
  id: '/over-megaonline',
  path: '/over-megaonline',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyverklaringRoute = PrivacyverklaringRouteImport.update({
  id: '/privacyverklaring',
  path: '/privacyverklaring',
  getParentRoute: () => rootRouteImport,
} as any)
const VeelgesteldeVragenRoute = VeelgesteldeVragenRouteImport.update({
  id: '/veelgestelde-vragen',
  path: '/veelgestelde-vragen',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesActiviteitenbedrijvenRoute =
  BranchesActiviteitenbedrijvenRouteImport.update({
    id: '/branches/activiteitenbedrijven',
    path: '/branches/activiteitenbedrijven',
    getParentRoute: () => rootRouteImport,
  } as any)
const BranchesDienstverlenersRoute = BranchesDienstverlenersRouteImport.update({
  id: '/branches/dienstverleners',
  path: '/branches/dienstverleners',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesNonProfitsRoute = BranchesNonProfitsRouteImport.update({
  id: '/branches/non-profits',
  path: '/branches/non-profits',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesOfferteaanvragenRoute =
  BranchesOfferteaanvragenRouteImport.update({
    id: '/branches/offerteaanvragen',
    path: '/branches/offerteaanvragen',
    getParentRoute: () => rootRouteImport,
  } as any)
const BranchesReserveringenRoute = BranchesReserveringenRouteImport.update({
  id: '/branches/reserveringen',
  path: '/branches/reserveringen',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesVerhuurbedrijvenRoute =
  BranchesVerhuurbedrijvenRouteImport.update({
    id: '/branches/verhuurbedrijven',
    path: '/branches/verhuurbedrijven',
    getParentRoute: () => rootRouteImport,
  } as any)
const DienstenConversieWebsiteRoute =
  DienstenConversieWebsiteRouteImport.update({
    id: '/diensten/conversie-website',
    path: '/diensten/conversie-website',
    getParentRoute: () => rootRouteImport,
  } as any)
const DienstenGroeiPartnershipRoute =
  DienstenGroeiPartnershipRouteImport.update({
    id: '/diensten/groei-partnership',
    path: '/diensten/groei-partnership',
    getParentRoute: () => rootRouteImport,
  } as any)
const DienstenIntegratiesRoute = DienstenIntegratiesRouteImport.update({
  id: '/diensten/integraties',
  path: '/diensten/integraties',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenSeoRoute = DienstenSeoRouteImport.update({
  id: '/diensten/seo',
  path: '/diensten/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenStarterWebsiteRoute = DienstenStarterWebsiteRouteImport.update({
  id: '/diensten/starter-website',
  path: '/diensten/starter-website',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenWebsiteOptimalisatieRoute =
  DienstenWebsiteOptimalisatieRouteImport.update({
    id: '/diensten/website-optimalisatie',
    path: '/diensten/website-optimalisatie',
    getParentRoute: () => rootRouteImport,
  } as any)
const DienstenWebsiteRedesignRoute = DienstenWebsiteRedesignRouteImport.update({
  id: '/diensten/website-redesign',
  path: '/diensten/website-redesign',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenWerkenBijWebsitesRoute =
  DienstenWerkenBijWebsitesRouteImport.update({
    id: '/diensten/werken-bij-websites',
    path: '/diensten/werken-bij-websites',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/contact': typeof ContactRoute
  '/gratis-websitescan': typeof GratisWebsitescanRoute
  '/over-megaonline': typeof OverMegaonlineRoute
  '/privacyverklaring': typeof PrivacyverklaringRoute
  '/veelgestelde-vragen': typeof VeelgesteldeVragenRoute
  '/branches/activiteitenbedrijven': typeof BranchesActiviteitenbedrijvenRoute
  '/branches/dienstverleners': typeof BranchesDienstverlenersRoute
  '/branches/non-profits': typeof BranchesNonProfitsRoute
  '/branches/offerteaanvragen': typeof BranchesOfferteaanvragenRoute
  '/branches/reserveringen': typeof BranchesReserveringenRoute
  '/branches/verhuurbedrijven': typeof BranchesVerhuurbedrijvenRoute
  '/diensten/conversie-website': typeof DienstenConversieWebsiteRoute
  '/diensten/groei-partnership': typeof DienstenGroeiPartnershipRoute
  '/diensten/integraties': typeof DienstenIntegratiesRoute
  '/diensten/seo': typeof DienstenSeoRoute
  '/diensten/starter-website': typeof DienstenStarterWebsiteRoute
  '/diensten/website-optimalisatie': typeof DienstenWebsiteOptimalisatieRoute
  '/diensten/website-redesign': typeof DienstenWebsiteRedesignRoute
  '/diensten/werken-bij-websites': typeof DienstenWerkenBijWebsitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/contact': typeof ContactRoute
  '/gratis-websitescan': typeof GratisWebsitescanRoute
  '/over-megaonline': typeof OverMegaonlineRoute
  '/privacyverklaring': typeof PrivacyverklaringRoute
  '/veelgestelde-vragen': typeof VeelgesteldeVragenRoute
  '/branches/activiteitenbedrijven': typeof BranchesActiviteitenbedrijvenRoute
  '/branches/dienstverleners': typeof BranchesDienstverlenersRoute
  '/branches/non-profits': typeof BranchesNonProfitsRoute
  '/branches/offerteaanvragen': typeof BranchesOfferteaanvragenRoute
  '/branches/reserveringen': typeof BranchesReserveringenRoute
  '/branches/verhuurbedrijven': typeof BranchesVerhuurbedrijvenRoute
  '/diensten/conversie-website': typeof DienstenConversieWebsiteRoute
  '/diensten/groei-partnership': typeof DienstenGroeiPartnershipRoute
  '/diensten/integraties': typeof DienstenIntegratiesRoute
  '/diensten/seo': typeof DienstenSeoRoute
  '/diensten/starter-website': typeof DienstenStarterWebsiteRoute
  '/diensten/website-optimalisatie': typeof DienstenWebsiteOptimalisatieRoute
  '/diensten/website-redesign': typeof DienstenWebsiteRedesignRoute
  '/diensten/werken-bij-websites': typeof DienstenWerkenBijWebsitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/contact': typeof ContactRoute
  '/gratis-websitescan': typeof GratisWebsitescanRoute
  '/over-megaonline': typeof OverMegaonlineRoute
  '/privacyverklaring': typeof PrivacyverklaringRoute
  '/veelgestelde-vragen': typeof VeelgesteldeVragenRoute
  '/branches/activiteitenbedrijven': typeof BranchesActiviteitenbedrijvenRoute
  '/branches/dienstverleners': typeof BranchesDienstverlenersRoute
  '/branches/non-profits': typeof BranchesNonProfitsRoute
  '/branches/offerteaanvragen': typeof BranchesOfferteaanvragenRoute
  '/branches/reserveringen': typeof BranchesReserveringenRoute
  '/branches/verhuurbedrijven': typeof BranchesVerhuurbedrijvenRoute
  '/diensten/conversie-website': typeof DienstenConversieWebsiteRoute
  '/diensten/groei-partnership': typeof DienstenGroeiPartnershipRoute
  '/diensten/integraties': typeof DienstenIntegratiesRoute
  '/diensten/seo': typeof DienstenSeoRoute
  '/diensten/starter-website': typeof DienstenStarterWebsiteRoute
  '/diensten/website-optimalisatie': typeof DienstenWebsiteOptimalisatieRoute
  '/diensten/website-redesign': typeof DienstenWebsiteRedesignRoute
  '/diensten/werken-bij-websites': typeof DienstenWerkenBijWebsitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/algemene-voorwaarden'
    | '/contact'
    | '/gratis-websitescan'
    | '/over-megaonline'
    | '/privacyverklaring'
    | '/veelgestelde-vragen'
    | '/branches/activiteitenbedrijven'
    | '/branches/dienstverleners'
    | '/branches/non-profits'
    | '/branches/offerteaanvragen'
    | '/branches/reserveringen'
    | '/branches/verhuurbedrijven'
    | '/diensten/conversie-website'
    | '/diensten/groei-partnership'
    | '/diensten/integraties'
    | '/diensten/seo'
    | '/diensten/starter-website'
    | '/diensten/website-optimalisatie'
    | '/diensten/website-redesign'
    | '/diensten/werken-bij-websites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/algemene-voorwaarden'
    | '/contact'
    | '/gratis-websitescan'
    | '/over-megaonline'
    | '/privacyverklaring'
    | '/veelgestelde-vragen'
    | '/branches/activiteitenbedrijven'
    | '/branches/dienstverleners'
    | '/branches/non-profits'
    | '/branches/offerteaanvragen'
    | '/branches/reserveringen'
    | '/branches/verhuurbedrijven'
    | '/diensten/conversie-website'
    | '/diensten/groei-partnership'
    | '/diensten/integraties'
    | '/diensten/seo'
    | '/diensten/starter-website'
    | '/diensten/website-optimalisatie'
    | '/diensten/website-redesign'
    | '/diensten/werken-bij-websites'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/algemene-voorwaarden'
    | '/contact'
    | '/gratis-websitescan'
    | '/over-megaonline'
    | '/privacyverklaring'
    | '/veelgestelde-vragen'
    | '/branches/activiteitenbedrijven'
    | '/branches/dienstverleners'
    | '/branches/non-profits'
    | '/branches/offerteaanvragen'
    | '/branches/reserveringen'
    | '/branches/verhuurbedrijven'
    | '/diensten/conversie-website'
    | '/diensten/groei-partnership'
    | '/diensten/integraties'
    | '/diensten/seo'
    | '/diensten/starter-website'
    | '/diensten/website-optimalisatie'
    | '/diensten/website-redesign'
    | '/diensten/werken-bij-websites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AlgemeneVoorwaardenRoute: typeof AlgemeneVoorwaardenRoute
  ContactRoute: typeof ContactRoute
  GratisWebsitescanRoute: typeof GratisWebsitescanRoute
  OverMegaonlineRoute: typeof OverMegaonlineRoute
  PrivacyverklaringRoute: typeof PrivacyverklaringRoute
  VeelgesteldeVragenRoute: typeof VeelgesteldeVragenRoute
  BranchesActiviteitenbedrijvenRoute: typeof BranchesActiviteitenbedrijvenRoute
  BranchesDienstverlenersRoute: typeof BranchesDienstverlenersRoute
  BranchesNonProfitsRoute: typeof BranchesNonProfitsRoute
  BranchesOfferteaanvragenRoute: typeof BranchesOfferteaanvragenRoute
  BranchesReserveringenRoute: typeof BranchesReserveringenRoute
  BranchesVerhuurbedrijvenRoute: typeof BranchesVerhuurbedrijvenRoute
  DienstenConversieWebsiteRoute: typeof DienstenConversieWebsiteRoute
  DienstenGroeiPartnershipRoute: typeof DienstenGroeiPartnershipRoute
  DienstenIntegratiesRoute: typeof DienstenIntegratiesRoute
  DienstenSeoRoute: typeof DienstenSeoRoute
  DienstenStarterWebsiteRoute: typeof DienstenStarterWebsiteRoute
  DienstenWebsiteOptimalisatieRoute: typeof DienstenWebsiteOptimalisatieRoute
  DienstenWebsiteRedesignRoute: typeof DienstenWebsiteRedesignRoute
  DienstenWerkenBijWebsitesRoute: typeof DienstenWerkenBijWebsitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemene-voorwaarden': {
      id: '/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof AlgemeneVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gratis-websitescan': {
      id: '/gratis-websitescan'
      path: '/gratis-websitescan'
      fullPath: '/gratis-websitescan'
      preLoaderRoute: typeof GratisWebsitescanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-megaonline': {
      id: '/over-megaonline'
      path: '/over-megaonline'
      fullPath: '/over-megaonline'
      preLoaderRoute: typeof OverMegaonlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacyverklaring': {
      id: '/privacyverklaring'
      path: '/privacyverklaring'
      fullPath: '/privacyverklaring'
      preLoaderRoute: typeof PrivacyverklaringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veelgestelde-vragen': {
      id: '/veelgestelde-vragen'
      path: '/veelgestelde-vragen'
      fullPath: '/veelgestelde-vragen'
      preLoaderRoute: typeof VeelgesteldeVragenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/activiteitenbedrijven': {
      id: '/branches/activiteitenbedrijven'
      path: '/branches/activiteitenbedrijven'
      fullPath: '/branches/activiteitenbedrijven'
      preLoaderRoute: typeof BranchesActiviteitenbedrijvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/dienstverleners': {
      id: '/branches/dienstverleners'
      path: '/branches/dienstverleners'
      fullPath: '/branches/dienstverleners'
      preLoaderRoute: typeof BranchesDienstverlenersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/non-profits': {
      id: '/branches/non-profits'
      path: '/branches/non-profits'
      fullPath: '/branches/non-profits'
      preLoaderRoute: typeof BranchesNonProfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/offerteaanvragen': {
      id: '/branches/offerteaanvragen'
      path: '/branches/offerteaanvragen'
      fullPath: '/branches/offerteaanvragen'
      preLoaderRoute: typeof BranchesOfferteaanvragenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/reserveringen': {
      id: '/branches/reserveringen'
      path: '/branches/reserveringen'
      fullPath: '/branches/reserveringen'
      preLoaderRoute: typeof BranchesReserveringenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/verhuurbedrijven': {
      id: '/branches/verhuurbedrijven'
      path: '/branches/verhuurbedrijven'
      fullPath: '/branches/verhuurbedrijven'
      preLoaderRoute: typeof BranchesVerhuurbedrijvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten/conversie-website': {
      id: '/diensten/conversie-website'
      path: '/diensten/conversie-website'
      fullPath: '/diensten/conversie-website'
      preLoaderRoute: typeof DienstenConversieWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten/groei-partnership': {
      id: '/diensten/groei-partnership'
      path: '/diensten/groei-partnership'
      fullPath: '/diensten/groei-partnership'
      preLoaderRoute: typeof DienstenGroeiPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten/integraties': {
      id: '/diensten/integraties'
      path: '/diensten/integraties'
      fullPath: '/diensten/integraties'
      preLoaderRoute: typeof DienstenIntegratiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten/seo': {
      id: '/diensten/seo'
      path: '/diensten/seo'
      fullPath: '/diensten/seo'
      preLoaderRoute: typeof DienstenSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten/starter-website': {
      id: '/diensten/starter-website'
      path: '/diensten/starter-website'
      fullPath: '/diensten/starter-website'
      preLoaderRoute: typeof DienstenStarterWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten/website-optimalisatie': {
      id: '/diensten/website-optimalisatie'
      path: '/diensten/website-optimalisatie'
      fullPath: '/diensten/website-optimalisatie'
      preLoaderRoute: typeof DienstenWebsiteOptimalisatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten/website-redesign': {
      id: '/diensten/website-redesign'
      path: '/diensten/website-redesign'
      fullPath: '/diensten/website-redesign'
      preLoaderRoute: typeof DienstenWebsiteRedesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten/werken-bij-websites': {
      id: '/diensten/werken-bij-websites'
      path: '/diensten/werken-bij-websites'
      fullPath: '/diensten/werken-bij-websites'
      preLoaderRoute: typeof DienstenWerkenBijWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AlgemeneVoorwaardenRoute: AlgemeneVoorwaardenRoute,
  ContactRoute: ContactRoute,
  GratisWebsitescanRoute: GratisWebsitescanRoute,
  OverMegaonlineRoute: OverMegaonlineRoute,
  PrivacyverklaringRoute: PrivacyverklaringRoute,
  VeelgesteldeVragenRoute: VeelgesteldeVragenRoute,
  BranchesActiviteitenbedrijvenRoute: BranchesActiviteitenbedrijvenRoute,
  BranchesDienstverlenersRoute: BranchesDienstverlenersRoute,
  BranchesNonProfitsRoute: BranchesNonProfitsRoute,
  BranchesOfferteaanvragenRoute: BranchesOfferteaanvragenRoute,
  BranchesReserveringenRoute: BranchesReserveringenRoute,
  BranchesVerhuurbedrijvenRoute: BranchesVerhuurbedrijvenRoute,
  DienstenConversieWebsiteRoute: DienstenConversieWebsiteRoute,
  DienstenGroeiPartnershipRoute: DienstenGroeiPartnershipRoute,
  DienstenIntegratiesRoute: DienstenIntegratiesRoute,
  DienstenSeoRoute: DienstenSeoRoute,
  DienstenStarterWebsiteRoute: DienstenStarterWebsiteRoute,
  DienstenWebsiteOptimalisatieRoute: DienstenWebsiteOptimalisatieRoute,
  DienstenWebsiteRedesignRoute: DienstenWebsiteRedesignRoute,
  DienstenWerkenBijWebsitesRoute: DienstenWerkenBijWebsitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
